### ISSUE TITLE
Add regular checkbox (none of)

### ISSUE THREAD

**Issue by azhengster** [plocket/docassemble-ALAutomatedTestingTests#31]

**Comment by plocket** [comment]
Sorry we didn't go over some of our conventions. One thing we do is keep issues open till the changes have been accepted and merged into the default branch (main) so they're part of the codebase everyone is working from. We'll get these merged soon and it'll get closed at that time. Thank you!

**Comment by azhengster** [comment]
Closed bc it's a duplicate issue
