### ISSUE TITLE
Github info screen: Provide an example of required URL

### ISSUE THREAD

**Issue by plocket** [plocket/docassemble-ALAutomatedTestingTests#50]
Provide an example of the kind of URL that is required here? E.g., `https://github.com/plocket/docassemble-ALAutomatedTestingTests`

_Originally posted by @niharikasingh in https://github.com/plocket/docassemble-ALAutomatedTestingTests/pull/42#discussion_r583339891_

**Comment by plocket** [comment]
Is this done already?

**Comment by niharikasingh** [comment]
Yeah I believe I saw this.
