### ISSUE TITLE
Create payload with `json.dumps` or f-string

### ISSUE THREAD

**Issue by plocket** [plocket/docassemble-ALAutomatedTestingTests#54]
This might be easier to read with an f-string. Something like 
```
>>> name = "Eric"
>>> age = 74
>>> f"Hello, {name}. You are {age}."
```
Source: https://realpython.com/python-f-strings/

> Or creating a regular dict and then `json.dumps`ing it to turn it into a string.

_Originally posted by @niharikasingh in https://github.com/plocket/docassemble-ALAutomatedTestingTests/pull/53#discussion_r584046562_

[Edit to add response:]

> I have not seen that way of composing strings in python before! All the ways I've seen it done have been incredibly clunky. This is much better.
> 
> I really like the idea of json.dumps too. It seems scalable. I'd seen it around, but wasn't sure of its use and didn't take the time to find out.
> 
> Which do you think would be a better fit?

**Comment by niharikasingh** [comment]
From https://github.com/plocket/docassemble-ALAutomatedTestingTests/pull/53#discussion_r584446253

> I think `json.dumps` would be a better fit here. That seems more in line with what we're trying to do: create a dictionary payload that is represented as a string.

**Comment by plocket** [comment]
I really like the structure proposed here, but I think it will be superceded by the [PyGithub secrets interface I missed](https://github.com/plocket/docassemble-ALAutomatedTestingTests/issues/37#issuecomment-792723071).
