### ISSUE TITLE
Discuss changing repo name or scope

### ISSUE THREAD

**Issue by plocket** [plocket/docassemble-ALAutomatedTestingTests#71]
It's basically turning into a repo that
1. Tests the testing library.
2. Contains user-facing tools to help developers make tests.

The only current user-facing tool is the one that helps get a developer set up, but if this is repo is going to be multi-purpose in this way, we could move the test generator here too. I'm not sure it would be an interview as it would actually be harder to create what now exists within a da package and I hope we can look into more features for it that also may not mesh well with a da package.

That said, we could also decide to split them up into... 3 repos?
1. Testing library.
2. Package for testing testing library.
3. Tools to help developers make tests.

It's annoying to have so many repos lying around, but it would be a bit cleaner. Thoughts?

**Comment by niharikasingh** [comment]
Notes:

We have three repositories:
1. `docassemble-cucumber`: The testing framework 
2. `ALAutomatedTestingTests`: Two uses: (1) tests `docassemble-cucumber` (2) helps developers set up tests in their own repository 
3. `AL_story`: Given JSON, creates cucumber tests

**Comment by plocket** [comment]
Made issues for followup:
- #153 for merging
- #154 for name change
